### ISSUE TITLE
Knight moves

### ISSUE THREAD

**Issue by ryomakawakami** [ryomakawakami/chess-ai#1]
Have to add check to make sure that the square that you're appending doesn't have a piece of self.color on it. Something like:
```
if x < 7 and y < 6 and squares[x + 1][y + 2] == None:
    if squares[x + 1][y + 2].color != self.color:
        self.moves.append((x + 1, y + 1))
```
This will fix the capture issue too.

Also, make sure to append a tuple (using double parentheses as shown above in my code.

**Comment by ryomakawakami** [comment]
Bad code ^
Good code v

```
if x < 7 and y < 6:
    if squares[x + 1][y + 2] == None or squares[x + 1][y + 2].color != self.color:
        self.moves.append((x + 1, y + 1))
```

**Comment by ryomakawakami** [comment]
Check checkmate

**Comment by yiyanghuang314** [comment]
Used special yiyang piece to avoid checkmate.
